<footer>
    <span id="GITHUB"><a href="https://github.com/NonstopCola/Web-Technologies-Final-Project" target="_blank">Our Projects</a></span>

    <span id="JIRA"><a href="https://jktn.atlassian.net/jira/software/projects/SCRUM/summary" target="_self">Our Plans</a></span>

    <span id="JKTNCopy">&copy;<a href="./index.php" target="_self">JKTN</a></span>
        <!-- Created a footer that contains the copyright and JIRA link -->
</footer>