<?php
session_start();
require_once './settings.php';
$activePage = 'jobs';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include './header.inc'; ?>
    <title>Available Jobs</title>
</head>
<body>
    <div class="logoContainer">
        <img src="./images/final_logo.png" alt="logo of company" id="Logo">
    </div>

    <h1>Available Jobs</h1>

    <?php include './nav.inc'; ?>

    <div id="main">
        <aside id="aside">
            <p>Applicants for all jobs must be willing to work in office at least 3 days a week</p>
        </aside>

        <?php
        // Create jobs table if it does not exist
        $create_table = "CREATE TABLE IF NOT EXISTS `jobs` (
            `title` varchar(50) NOT NULL PRIMARY KEY,
            `reference_number` varchar(5) NOT NULL,
            `summary` text NOT NULL,
            `responsibilities` text NOT NULL,
            `essential` text NOT NULL,
            `preferred` text NOT NULL,
            `report` varchar(50) NOT NULL,
            `salary` varchar(20) NOT NULL
        )";

        if (!mysqli_query($conn, $create_table)) {
            echo "<p>Error creating jobs table: " . mysqli_error($conn) . "</p>";
        }

        // Check if jobs are present
        $sql = "SELECT * FROM jobs ORDER BY title";
        $result = mysqli_query($conn, $sql);

        if (mysqli_num_rows($result) == 0) {
            // insert jobs into table if empty
            $pre_job = [
                [
                    // Title of job
                    'title' => "Network Administrator",
                    // Reference number of job
                    'reference_number' => "K9986",
                    // summary of the network administrator job generated by chatgpt.com using prompt "write a job summary for a network administrator"
                    'summary' => "We are seeking a skilled and detail-oriented Network Administrator to manage, maintain, and optimize our organization's network infrastructure. The ideal candidate will be responsible for ensuring the stability, security, and efficiency of data communications and network services across all departments. This role involves configuring and supporting LANs, WANs, VPNs, firewalls, and other network hardware and software. The Network Administrator will also monitor network performance, troubleshoot issues, and implement upgrades to support evolving business needs. Strong analytical skills, a proactive attitude, and the ability to work both independently and as part of a team are essential for success in this role.",
                    // Responsibilities of the network administrator job generated by chatgpt.com using prompt "write a list of responsibilities for a network administrator and split it into essential and preferred"
                    'responsibilities' => "<ol><li>Install, configure, and maintain network hardware and software.</li><li>Monitor network performance and troubleshoot issues as they arise.</li><li>Implement security measures to protect the network from unauthorized access.</li><li>Manage and maintain firewalls, VPNs, and intrusion detection systems.</li><li>Collaborate with IT teams to support network-related projects and initiatives.</li><li>Document network configurations, procedures, and policies.</li><li>Provide technical support to end-users regarding network-related issues.</li></ol>",
                    'essential' => "<ul><li>Bachelor's degree in Computer Science, Information Technology, or a related field.</li><li>5 Years of proven experience as a Network Administrator or similar role.</li><li>Experience with network security practices and tools.</li><li>Familiarity with firewalls, VPNs, and intrusion detection systems.</li><li>Strong troubleshooting and problem-solving skills.</li><li>Excellent communication and interpersonal abilities.</li><li>High level understanding of the coding language Python.</li><li>High level understanding of the coding language Perl.</li></ul>",
                    'preferred' => "<ul><li>Experience with network monitoring tools (e.g., Wireshark, SolarWinds).</li><li>Ability to work in a fast-paced environment and manage multiple tasks.</li><li>Ability to excel when working from home and or being alone.</li></ul>",
                    // Direct report for the network administrator job.
                    'report' => "Direct report - Lead Network Administrator",
                    // Salary range for the network administrator job.
                    'salary' => "90,000 - 110,000"
                ],
                [
                    // Title of job
                    'title' => "Software Developer",
                    // Reference number of job
                    'reference_number' => "J7652",
                    // summary of the software developer job generated by chatgpt.com using prompt "write a job summary for a software developer"
                    'summary' => "We are seeking a skilled and detail-oriented Software Developer to design, develop, and maintain high-quality software applications that meet the evolving needs of our organization. The ideal candidate will be responsible for writing clean, efficient, and scalable code, collaborating with cross-functional teams to deliver robust software solutions, and continuously improving existing applications. This role involves participating in the full software development lifecycle, including requirements analysis, coding, testing, deployment, and maintenance. The Software Developer will also troubleshoot and resolve software defects, stay current with emerging technologies, and contribute to code reviews and best practices. Strong problem-solving abilities, excellent communication skills, and a commitment to delivering reliable software both independently and collaboratively are essential for success in this role.",
                    // Responsibilities of the software developer job generated by chatgpt.com using prompt "write a list of responsibilities for a software developer and split it into essential and preferred"
                    'responsibilities' => "<ol><li>Design, develop, and maintain software applications.</li><li>Write clean, scalable, and efficient code.</li><li>Debug and troubleshoot software issues.</li><li>Participate in code reviews and provide constructive feedback.</li><li>Stay updated with emerging technologies and industry trends.</li></ol>",
                    'essential' => "<ul><li>Bachelor's degree in Computer Science, Information Technology, or a related field.</li><li>5 Years of proven experience as a Software Developer or similar role.</li><li>Experience with multiple coding languages such as python, c++ and java.</li><li>Strong troubleshooting and problem-solving skills.</li><li>Excellent communication and interpersonal abilities.</li></ul>",
                    'preferred' => "<ul><li>Strong portfolio of prior projects in the field.</li><li>Ability to work in a fast-paced environment and manage multiple tasks.</li><li>Ability to excel when working from home and or being alone.</li></ul>",
                    // Direct report for the software developer job.
                    'report' => "Direct report - Lead Software Developer",
                    // Salary range for the software developer job.
                    'salary' => "80,000 - 100,000"
                ],
                [
                    // Title of job
                    'title' => "Cybersecurity Specialist",
                    // Reference number of job
                    'reference_number' => "S9475",
                    // summary of the cybersecurity specialist job generated by chatgpt.com using prompt "write a job summary for a cybersecurity specialist"
                    'summary' => "We are seeking a highly skilled and detail-oriented Cybersecurity Specialist to join our IT security team. The ideal candidate will be responsible for protecting our organization's computer systems and networks from cyber threats. This role involves monitoring network traffic, identifying vulnerabilities, implementing security measures, and responding to security incidents. The Cybersecurity Specialist will also conduct risk assessments, develop security policies, and provide training to staff on best practices for data protection. Strong analytical skills, a proactive approach to problem-solving, and the ability to work both independently and collaboratively are essential for success in this role.",
                    // Responsibilities of the cybersecurity specialist job generated by chatgpt.com using prompt "write a list of responsibilities for a cybersecurity specialist and split it into essential and preferred"
                    'responsibilities' => "<ol><li>Monitor network traffic for suspicious activity and potential threats.</li><li>Conduct vulnerability assessments and penetration testing.</li><li>Implement security measures to protect sensitive data and systems.</li><li>Respond to security incidents and breaches, conducting investigations as needed.</li><li>Develop and maintain security policies, procedures, and documentation.</li><li>Provide training and support to staff on cybersecurity best practices.</li></ol>",
                    'essential' => "<ul><li>Bachelor's degree in Cybersecurity, Information Technology, or a related field.</li><li>5 Years of proven experience as a Cybersecurity Specialist or similar role.</li><li>Experience with security tools and technologies (e.g., firewalls, intrusion detection systems).</li><li>Strong understanding of network protocols and security practices.</li></ul>",
                    'preferred' => "<ul><li>Ability to work in a fast-paced environment and manage multiple tasks.</li><li>Ability to excel when working from home and or being alone.</li><li>Excellent analytical and problem-solving skills.</li><li>Strong communication and interpersonal abilities.</li></ul>",
                    // Direct report for the cybersecurity specialist job.
                    'report' => "Direct report - Lead Cybersecurity Specialist",
                    // Salary range for the cybersecurity specialist job.
                    'salary' => "115,000 - 168,000"
                ]
            ];
            // Insert the predefined jobs into the database
            $stmt = mysqli_prepare($conn, "INSERT INTO jobs (title, reference_number, summary, responsibilities, essential, preferred, report, salary) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            // Check if the statement was prepared successfully
            if ($stmt) {
                // Loop through the predefined jobs and bind parameters
                foreach ($pre_job as $job) {
                    mysqli_stmt_bind_param(
                        $stmt,
                        "ssssssss",
                        $job['title'],
                        $job['reference_number'],
                        $job['summary'],
                        $job['responsibilities'],
                        $job['essential'],
                        $job['preferred'],
                        $job['report'],
                        $job['salary']
                    );
                    if (!mysqli_stmt_execute($stmt)) {
                        // If the execution fails, display an error message
                        echo "<p>Error inserting job: " . mysqli_stmt_error($stmt) . "</p>";
                    }
                }
                mysqli_stmt_close($stmt);
            } else {
                // If the statement preparation fails, display an error message
                echo "<p>Prepare failed: " . mysqli_error($conn) . "</p>";
            }
            // Re-fetch the jobs after inserting
            $result = mysqli_query($conn, $sql); // Re-fetch after inserting
        }
        // Display the jobs
        if (!$result) {
            echo "<p>Error fetching jobs: " . mysqli_error($conn) . "</p>";
        } elseif (mysqli_num_rows($result) == 0) {
            echo "<p>No jobs available at the moment.</p>";
        } else {
                 while ($row = mysqli_fetch_assoc($result)) {
                    $title = htmlspecialchars($row['title']);
                    $ref = htmlspecialchars($row['reference_number']);
                    $summary = nl2br(htmlspecialchars($row['summary']));
                    $responsibilities = $row['responsibilities'];
                    $essential = $row['essential'];
                    $preferred = $row['preferred'];
                    $report = htmlspecialchars($row['report']);
                    $salary = htmlspecialchars($row['salary']);
                    $id = strtolower(str_replace(' ', '_', $title));

                    echo "<section id=\"$id\">
                        <h2>$title</h2>
                        <p class=\"reference\">Reference number - $ref</p>
                        <p><strong>Summary</strong></p>
                        <p>$summary</p>

                        <div class=\"details\">
                            <div class=\"responsibilities\">
                                <p><strong>Responsibilities</strong></p>
                                $responsibilities
                            </div>
                            <div class=\"qualifications\">
                                <div class=\"essential\">
                                    <p><strong>Essential Qualifications</strong></p>
                                    $essential
                                </div>
                                <div class=\"preferred\">
                                    <p><strong>Preferred Qualifications</strong></p>
                                    $preferred
                                </div>
                            </div>
                            <div class=\"other_info\">
                                <p class=\"report\">$report</p>
                                <p class=\"salary\">Salary range - $salary</p>
                            </div>
                        </div>
                    </section>";
                }
        }
        ?>

        <?php include './footer.inc'; ?>
    </div>
</body>
</html>
