<ul id="nav">
    <!-- Used chatgpt to create the class command -->
    <li><a class="<?= ($activePage == 'index') ? 'active' : '' ?>" href="./index.php">Home</a></li>
    <li><a class="<?= ($activePage == 'about') ? 'active' : '' ?>" href="./about.php">About</a></li>
    <li><a class="<?= ($activePage == 'jobs') ? 'active' : '' ?>" href="./jobs.php">Jobs</a></li>
    <li><a class="<?= ($activePage == 'apply') ? 'active' : '' ?>" href="./apply.php">Apply</a></li>
    <li class="mail"><a href="mailto:jktngroup4@gmail.com"><span>info@jktn.com.au</span></a></li>
</ul>